"""Backfill the Obsidian vault from the autonomy trail — the graph was starving.

The supervisor runs with DOCS_ENABLED=0 by design (documentation must never block
training), which means the vault's knowledge graph silently stopped growing the moment
the auto loop became the primary mode: 100+ iterations of the project's most
interesting work produced ZERO notes. The raw data was all in autonomy.jsonl.

This module converts the trail into a densely-linked note web, no LLM required
(factual templating — deterministic, instant, idempotent):

    vault/31-iterations/Iter NNN.md      one note per iteration (metrics, decision,
                                         reason), linked to its hunt, map and concepts
    vault/30-runs/Hunt NN.md             one note per regime segment (trajectory table,
                                         best iter, boundary cause)
    vault/20-concepts/*.md               concept stubs for every mechanism that fired
                                         (created only if missing — hand-edits survive)

Idempotent: generated notes carry a marker and are rewritten on each sync; concept
notes are only created, never overwritten.

    doom-cli vault            # sync the graph from the trail
"""
from __future__ import annotations

import json
import os
from typing import Dict, List, Optional

_MARKER = "<!-- auto-generated by trail_notes — edits will be overwritten -->"

# Concepts detected from iteration data → (note name, one-line definition).
_CONCEPTS = {
    "plateau": ("Plateau Escape",
                "Escalating structural interventions (L1 knob reset → L2 map switch → "
                "L3 best-config revert + entropy → L4 history purge) when the loop "
                "stops improving. The brain is never discarded."),
    "trend": ("Behavior Trends",
              "Cross-run behaviour flags (circling, passivity, spray); a flag persisting "
              "in ≥60% of runs biases the next reward proposal."),
    "semantic": ("Semantic Memory",
                 "Vector-DB recall over past situations ('seen this before — what "
                 "worked?'), using local embeddings."),
    "route": ("Geodesic Route",
              "Distance-to-exit measured ALONG WALKABLE PATHS (BFS over WAD walls, "
              "directional steps, sub-body slits). Euclidean distance lies in a maze."),
    "memory": ("Memory Policy",
               "Persistent death-pattern store driving reward proposals; never repeats "
               "a change a past experiment disproved."),
    "exit_shaping": ("Exit Proximity Shaping",
                     "Signed potential-based reward for geodesic progress toward the "
                     "exit; off-route positions read worse than anywhere on the route "
                     "(anti pit-dive)."),
    "solo": ("Solo Mode",
             "All skill assists disabled (aim/door-nav/best-weapon); doors may still "
             "open on contact (SOLO_AUTO_USE) — map mechanics, not skill."),
    "keep_revert": ("Keep-Revert Guardrail",
                    "A proposed config survives only if the composite score holds "
                    "within 0.05 of the regime-local best; otherwise it is rolled back."),
}


def _load_trail(memory_dir: str) -> List[dict]:
    path = os.path.join(memory_dir, "autonomy.jsonl")
    rows: List[dict] = []
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            for line in f:
                if line.strip():
                    try:
                        rows.append(json.loads(line))
                    except json.JSONDecodeError:
                        continue
    return rows


def _segments(rows: List[dict]) -> List[List[dict]]:
    """Split the trail into regime segments (hunts): a new segment starts at an escape
    marker or a map change — the same boundaries the score baseline uses."""
    segs: List[List[dict]] = []
    cur: List[dict] = []
    prev_map: Optional[str] = None
    for r in rows:
        m = (r.get("env") or {}).get("MAPS")
        if cur and ((r.get("plateau_level") or 0) > 0 or (prev_map is not None and m != prev_map)):
            segs.append(cur)
            cur = []
        cur.append(r)
        prev_map = m
    if cur:
        segs.append(cur)
    return segs


def _concepts_for(row: dict) -> List[str]:
    """Which concept notes this iteration should link to, from its decision text."""
    text = f"{row.get('reason', '')} {row.get('_next_reason', '')}".lower()
    out = ["keep_revert"]
    if row.get("plateau_level"):
        out.append("plateau")
    if "persistent '" in text or "trend" in text:
        out.append("trend")
    if "semantic recall" in text:
        out.append("semantic")
    if "memory:" in text:
        out.append("memory")
    if "exit_prox" in text or "route_progress" in text or "dying of clock" in text:
        out.append("exit_shaping")
    if (row.get("metrics") or {}).get("route_progress") is not None:
        out.append("route")
    return out


def _pct(v) -> str:
    return f"{v:.1%}" if isinstance(v, (int, float)) else "—"


def _iter_note(row: dict, hunt_name: str) -> str:
    m = row.get("metrics") or {}
    links = " · ".join(f"[[{_CONCEPTS[c][0]}]]" for c in dict.fromkeys(_concepts_for(row)))
    doom_map = (row.get("env") or {}).get("MAPS", "?")
    verdict = "✅ KEEP" if row.get("kept") else "↩️ REVERT"
    return f"""---
type: auto-iteration
iter: {row['iter']}
map: {doom_map}
score: {round(row.get('score', 0), 3)}
kept: {bool(row.get('kept'))}
---
{_MARKER}

# Iter {row['iter']} — {verdict} (score {row.get('score', 0):.2f})

Part of [[{hunt_name}]] on [[{doom_map}]].

| metric | value |
|---|---|
| score | {row.get('score', 0):.3f} |
| kills/ep | {m.get('kills_per_episode', '—')} |
| explored | {_pct(m.get('explored_fraction'))} |
| route progress (mean/best) | {_pct(m.get('route_progress'))} / {_pct(m.get('route_progress_best'))} |
| exit rate | {_pct(m.get('exit_rate'))} |
| deaths / timeouts | {_pct(m.get('death_rate'))} / {_pct(m.get('timeout_rate'))} |

**Decision basis:** {row.get('reason', '—')}

**Next proposal:** {row.get('_next_reason', '—')}

Concepts: {links}
"""


def _hunt_note(seg: List[dict], name: str, boundary_cause: str) -> str:
    first, last = seg[0], seg[-1]
    best = max(seg, key=lambda r: r.get("score", -1e9))
    doom_map = (last.get("env") or {}).get("MAPS", "?")
    rows = "\n".join(
        f"| [[Iter {r['iter']}]] | {r.get('score', 0):.2f} | "
        f"{'KEEP' if r.get('kept') else 'revert'} | "
        f"{_pct((r.get('metrics') or {}).get('route_progress'))} | "
        f"{_pct((r.get('metrics') or {}).get('exit_rate'))} |"
        for r in seg)
    kept_n = sum(1 for r in seg if r.get("kept"))
    return f"""---
type: hunt
iters: {first['iter']}-{last['iter']}
map: {doom_map}
best_score: {round(best.get('score', 0), 3)}
---
{_MARKER}

# {name} — iters {first['iter']}–{last['iter']} on [[{doom_map}]]

**Opened by:** {boundary_cause}
**Outcome:** {kept_n}/{len(seg)} kept · best score {best.get('score', 0):.2f} at [[Iter {best['iter']}]]

| iter | score | verdict | route | exit |
|---|---|---|---|---|
{rows}

See [[Autonomy Log]] · [[Plateau Escape]] · [[Keep-Revert Guardrail]]
"""


def sync(memory_dir: str, vault_path: str) -> Dict[str, int]:
    """Generate/refresh the note web. Returns counts per note kind."""
    rows = _load_trail(memory_dir)
    iters_dir = os.path.join(vault_path, "31-iterations")
    runs_dir = os.path.join(vault_path, "30-runs")
    concepts_dir = os.path.join(vault_path, "20-concepts")
    for d in (iters_dir, runs_dir, concepts_dir):
        os.makedirs(d, exist_ok=True)

    counts = {"iterations": 0, "hunts": 0, "concepts": 0}
    used_concepts: set = set()

    segs = _segments(rows)
    for si, seg in enumerate(segs, start=1):
        name = f"Hunt {si:02d}"
        first = seg[0]
        if first.get("plateau_level"):
            cause = f"plateau escape L{first['plateau_level']}"
        elif si == 1:
            cause = "session start"
        else:
            cause = "map/regime switch"
        with open(os.path.join(runs_dir, f"{name}.md"), "w", encoding="utf-8") as f:
            f.write(_hunt_note(seg, name, cause))
        counts["hunts"] += 1
        for r in seg:
            with open(os.path.join(iters_dir, f"Iter {r['iter']}.md"), "w",
                      encoding="utf-8") as f:
                f.write(_iter_note(r, name))
            counts["iterations"] += 1
            used_concepts.update(_concepts_for(r))

    # Concept stubs: create-only (hand edits survive forever).
    for key in used_concepts:
        title, definition = _CONCEPTS[key]
        path = os.path.join(concepts_dir, f"{title}.md")
        if not os.path.exists(path):
            with open(path, "w", encoding="utf-8") as f:
                f.write(f"---\ntype: concept\n---\n\n# {title}\n\n{definition}\n\n"
                        f"Backlinks from iterations connect here automatically.\n")
            counts["concepts"] += 1

    counts["orphans_linked"] = _write_moc(vault_path)
    return counts


import re as _re


def _write_moc(vault_path: str) -> int:
    """Map of Content: one generated hub note that links EVERY note in the vault,
    grouped by folder. In a knowledge graph an orphan node is invisible knowledge —
    this guarantees minimum degree 1 for every note (Obsidian draws the inbound edge).
    Returns how many notes were orphans (no [[links]] in OR out) before the MOC."""
    notes: List[str] = []
    linked_to: set = set()
    has_outlink: Dict[str, bool] = {}
    for root, dirs, files in os.walk(vault_path):
        dirs[:] = [d for d in dirs if not d.startswith(".")]
        for fn in files:
            if not fn.endswith(".md"):
                continue
            rel = os.path.relpath(os.path.join(root, fn), vault_path)
            name = fn[:-3]
            if name == "Graph Index":
                continue
            notes.append(rel)
            try:
                body = open(os.path.join(root, fn), encoding="utf-8").read()
            except OSError:
                continue
            outs = _re.findall(r"\[\[([^\]|#]+)", body)
            has_outlink[rel] = bool(outs)
            linked_to.update(o.strip() for o in outs)

    orphans = sum(1 for rel in notes
                  if not has_outlink.get(rel)
                  and os.path.basename(rel)[:-3] not in linked_to)

    by_folder: Dict[str, List[str]] = {}
    for rel in sorted(notes):
        folder = os.path.dirname(rel) or "."
        by_folder.setdefault(folder, []).append(os.path.basename(rel)[:-3])
    sections = "\n".join(
        f"\n## {folder}\n" + "\n".join(f"- [[{n}]]" for n in names)
        for folder, names in sorted(by_folder.items()))
    body = (f"---\ntype: moc\n---\n{_MARKER}\n\n# Graph Index\n\n"
            f"Every note in the vault, so nothing is an orphan in the graph view.\n"
            f"{sections}\n")
    idx_dir = os.path.join(vault_path, "00-index")
    os.makedirs(idx_dir, exist_ok=True)
    with open(os.path.join(idx_dir, "Graph Index.md"), "w", encoding="utf-8") as f:
        f.write(body)
    return orphans
